[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "vibrant"
[theme.templates]
builtin_ids = ["niri", "wezterm", "kcolorscheme"]
community_ids = ["zen-browser", "neovim", "discord", "yazi", "steam"]
